#!/usr/bin/env python3
"""
scripts/import_synthetic_tickets.py
=====================================
Reads the JSON file generated by Claude and inserts tickets into the DB.

Usage:
    cd backend
    python scripts/import_synthetic_tickets.py ../synthetic_tickets.json
"""

import json
import sys
import os

_BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _BACKEND_DIR)

from dotenv import load_dotenv
load_dotenv(os.path.join(_BACKEND_DIR, ".env"))

from database import SessionLocal
from models import Ticket, Category

CATEGORY_MAP = {
    "Billing": 1,
    "Technical": 2,
    "Account": 3,
    "Feature Request": 4,
    "General": 5,
    "Performance": 6,
}

VALID_PRIORITIES = {"low", "medium", "urgent"}

def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/import_synthetic_tickets.py <path_to_json_file>")
        sys.exit(1)

    filepath = sys.argv[1]
    with open(filepath, "r") as f:
        data = json.load(f)

    tickets = data if isinstance(data, list) else data.get("tickets", [])
    print(f"Found {len(tickets)} tickets in file.")

    db = SessionLocal()
    inserted = 0
    skipped = 0

    try:
        for t in tickets:
            priority = t.get("priority", "").strip().lower()
            category_name = t.get("category", "General").strip()
            title = t.get("title", "").strip()
            description = t.get("description", "").strip()

            if not title or not description:
                skipped += 1
                continue
            if priority not in VALID_PRIORITIES:
                print(f"  SKIP invalid priority '{priority}': {title[:50]}")
                skipped += 1
                continue

            category_id = CATEGORY_MAP.get(category_name, 5)  # default General

            ticket = Ticket(
                title=title,
                description=description,
                priority=priority,
                status="open",
                category_id=category_id,
                customer_id=1,  # assign to first user
            )
            db.add(ticket)
            inserted += 1

        db.commit()
        print(f"\nDone. Inserted: {inserted} | Skipped: {skipped}")
        print("Now re-run: python scripts/train_priority_classifier.py")

    except Exception as e:
        db.rollback()
        print(f"Error: {e}")
        raise
    finally:
        db.close()

if __name__ == "__main__":
    main()
